export const mockTasks = [
  {
    id: 1,
    title: 'Design project ERD and base API contract',
    project: 'FCJ Capstone Platform',
    assignee: 'Minh Tran',
    status: 'In Progress',
    priority: 'High',
    deadline: '2026-06-21',
  },
  {
    id: 2,
    title: 'Build login and register screens',
    project: 'Frontend Foundation',
    assignee: 'Linh Pham',
    status: 'Review',
    priority: 'Medium',
    deadline: '2026-06-18',
  },
  {
    id: 3,
    title: 'Prepare SQS email notification flow',
    project: 'Serverless Track',
    assignee: 'An Nguyen',
    status: 'To Do',
    priority: 'High',
    deadline: '2026-06-25',
  },
  {
    id: 4,
    title: 'Create task completion analytics mockup',
    project: 'Data Dashboard',
    assignee: 'Huy Le',
    status: 'Done',
    priority: 'Low',
    deadline: '2026-06-16',
  },
  {
    id: 5,
    title: 'Draft Bedrock AI assistant prompt flow',
    project: 'AI Assistant',
    assignee: 'Minh Tran',
    status: 'To Do',
    priority: 'Medium',
    deadline: '2026-06-28',
  },
]
